# Generated by Django 2.0.4 on 2018-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180417_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjournal',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
