# Generated by Django 2.0.4 on 2018-04-17 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180417_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityjournal',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
