# Generated by Django 2.0.4 on 2018-04-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180417_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityjournal',
            name='time_lapse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
